### ISSUE TITLE
Questions about your work

### ISSUE THREAD

**Issue by nikokks** [yifanzhang-pro/Kernel-SSL#1]
Hello ,

First of all, Congratualtions for your work !

I have a question about the performances of your technique:
Does it outperforms EMP-SSL method (https://arxiv.org/abs/2304.03977) ?
I did not see comparaison between the two works.

Best regards

**Comment by yifanzhang-pro** [comment]
Hello,

Thank you for your interest in our work and for your congratulations!

Regarding your question about the performance of our technique compared to EMP-SSL (https://arxiv.org/abs/2304.03977), we acknowledge that we did not include a direct comparison between the two methods in our work. However, it is important to note that many existing techniques, such as DINO and EMP-SSL, employ Multi-crop augmentation, which was not included in our comparison baselines.

We want to emphasize that our method can easily incorporate Multi-crop augmentation techniques, and we plan to include more experimental results in our future work to provide a comprehensive evaluation and comparison with other methods, including EMP-SSL. We appreciate your feedback, and it will help us further improve and validate the effectiveness of our approach.

Thank you again for your attention and support!

Best regards,
